import type { Metadata } from "next";
import { Roboto } from 'next/font/google';
import "./globals.css";
import { NavBar } from '../widgets/navigation';
import AuthProvider from './AuthProvider';

const roboto = Roboto({weight: ['400', '500', '700'], subsets: ['latin']});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={roboto.className}>
        <NavBar />
        {children}
        </body>
      </html>
    </AuthProvider>
  );
}
